[theme]
# Primary accent color for interactive elements.
primaryColor = '#e17055'

# Background color for the main content area.
backgroundColor= '#636e72'

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = '#2d3436'

# Color used for almost all text.
textColor = '000'

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"