[theme]
# Primary accent color for interactive elements.
primaryColor = '#74b9ff'

# Background color for the main content area.
backgroundColor= '#dfe6e9'

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = '#6c5ce7'

# Color used for almost all text.
textColor = '000'

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "sans serif"